Friend Module Constants
    Friend Const AbandonGameText = "Abandon Game"
    Friend Const SaveGameNamePrompt = "[olive]Save Game Name:[/]"
    Friend Const ConfirmAbandonPrompt = "[red]Are you sure you want to abandon the game?[/]"
    Friend Const EmbarkText = "Embark!"
    Friend Const GameLoadedMessage = "[lime]Game Loaded![/]"
    Friend Const GameSavedMessage = "[lime]Game Saved![/]"
    Friend Const GameTitle = "Gorachan's Vacation IV: Just the Tip"
    Friend Const LoadFailedMessage = "[red]Failed to load![/]"
    Friend Const LoadGameText = "Load Game"
    Friend Const MainMenuText = "Main Menu"
    Friend Const MainMenuTitle = "[olive]Main Menu:[/]"
    Friend Const NoText = "No"
    Friend Const OkText = "Ok"
    Friend Const OnwardText = "Onward!"
    Friend Const QuitPrompt = "[red]Are you sure you want to quit?[/]"
    Friend Const QuitText = "Quit"
    Friend Const SaveGameText = "Save Game"
    Friend Const ScumFilename = "scum.json"
    Friend Const ScumLoadText = "Scum Load"
    Friend Const ScumSaveText = "Scum Save"
    Friend Const ShameText = "No hugs for you, then!"
    Friend Const YesText = "Yes"
End Module
